#!/usr/bin/env bash

RED=$(tput setaf 1)
RESET=$(tput sgr0)

function main {
    SOCK=$(ls /tmp/ssh-*/agent.* 2>/dev/null | head -n 1)
    if [ "$SOCK" = "" ]; then
        # Launch a new ssh-agent

        >&2 echo "${RED}ssh-agent missing. Launching new one.${RESET}"
        eval $(ssh-agent) >/dev/null && ssh-add ~/.ssh/id_ed25519
        >&2 echo
    else
        # Reuse the existing ssh-agent

        PID1=$(echo "$SOCK" | sed 's|.*/agent\.||')
        PID2=$(($PID1 + 1))
        PID=$(ps aux | awk '{print $2}' | pcregrep "$PID1|$PID2")

        if [ "$PID" = "" ] && [ "$1" != "retry" ]; then
            # ssh-agent seems to be killed. Clean up the dir and retry again.

            rm -rf /tmp/ssh-*
            main retry
            return
        fi

        SSH_AGENT_PID="$PID"
        SSH_AUTH_SOCK="$SOCK"
    fi

    echo export SSH_AGENT_PID="$SSH_AGENT_PID"
    echo export SSH_AUTH_SOCK="$SSH_AUTH_SOCK"
}


if [ "$#" -gt 0 ]; then
    eval $(main); "$@"
else
    main
fi
