[colors.primary]
background = "0x101010"
foreground = "0x909090"

[font]
size = 14.0
normal = {family = "Ricty Diminished Discord for Powerline", style = "Regular"}
bold   = {family = "Ricty Diminished Discord for Powerline", style = "Bold"}
italic = {family = "Ricty Diminished Discord for Powerline", style = "Italic"}

[keyboard]
bindings = [
# (insert
#  (string-join
# (mapcar (lambda (c)
#           (let* ((lo (logand #x0f c))
#                  (hi (logand #xf0 c))
#                  (base (logand #x1f c))
#                  (cap (logior #x40 base)))
#             (cond
#              ((or (equal hi #x40)
#                   (equal hi #x50))
#               (format "  {mods = \"Super|Shift\", key = \"%c\", chars = \"\\u0014\\u%04x\"},\n" cap c))
#              ((or (equal hi #x60)
#                   (equal hi #x70))
#               (format "  {mods = \"Super\",       key = \"%c\", chars = \"\\u0014\\u%04x\"},\n" cap c))
#              (t
#               (error "not supported")))))

#         (append (number-sequence #x41 #x5a)
#                 (number-sequence #x61 #x7a)))
# ""))
  {mods = "Super|Shift", key = "A", chars = "\u0014\u0041"},
  {mods = "Super|Shift", key = "B", chars = "\u0014\u0042"},
  {mods = "Super|Shift", key = "C", chars = "\u0014\u0043"},
  {mods = "Super|Shift", key = "D", chars = "\u0014\u0044"},
  {mods = "Super|Shift", key = "E", chars = "\u0014\u0045"},
  {mods = "Super|Shift", key = "F", chars = "\u0014\u0046"},
  {mods = "Super|Shift", key = "G", chars = "\u0014\u0047"},
  {mods = "Super|Shift", key = "H", chars = "\u0014\u0048"},
  {mods = "Super|Shift", key = "I", chars = "\u0014\u0049"},
  {mods = "Super|Shift", key = "J", chars = "\u0014\u004a"},
  {mods = "Super|Shift", key = "K", chars = "\u0014\u004b"},
  {mods = "Super|Shift", key = "L", chars = "\u0014\u004c"},
  {mods = "Super|Shift", key = "M", chars = "\u0014\u004d"},
  {mods = "Super|Shift", key = "N", chars = "\u0014\u004e"},
  {mods = "Super|Shift", key = "O", chars = "\u0014\u004f"},
  {mods = "Super|Shift", key = "P", chars = "\u0014\u0050"},
  {mods = "Super|Shift", key = "Q", chars = "\u0014\u0051"},
  {mods = "Super|Shift", key = "R", chars = "\u0014\u0052"},
  {mods = "Super|Shift", key = "S", chars = "\u0014\u0053"},
  {mods = "Super|Shift", key = "T", chars = "\u0014\u0054"},
  {mods = "Super|Shift", key = "U", chars = "\u0014\u0055"},
  {mods = "Super|Shift", key = "V", chars = "\u0014\u0056"},
  {mods = "Super|Shift", key = "W", chars = "\u0014\u0057"},
  {mods = "Super|Shift", key = "X", chars = "\u0014\u0058"},
  {mods = "Super|Shift", key = "Y", chars = "\u0014\u0059"},
  {mods = "Super|Shift", key = "Z", chars = "\u0014\u005a"},
  {mods = "Super",       key = "A", chars = "\u0014\u0061"},
  {mods = "Super",       key = "B", chars = "\u0014\u0062"},
  {mods = "Super",       key = "C", chars = "\u0014\u0063"},
  {mods = "Super",       key = "D", chars = "\u0014\u0064"},
  {mods = "Super",       key = "E", chars = "\u0014\u0065"},
  {mods = "Super",       key = "F", chars = "\u0014\u0066"},
  {mods = "Super",       key = "G", chars = "\u0014\u0067"},
  {mods = "Super",       key = "H", chars = "\u0014\u0068"},
  {mods = "Super",       key = "I", chars = "\u0014\u0069"},
  {mods = "Super",       key = "J", chars = "\u0014\u006a"},
  {mods = "Super",       key = "K", chars = "\u0014\u006b"},
  {mods = "Super",       key = "L", chars = "\u0014\u006c"},
  {mods = "Super",       key = "M", chars = "\u0014\u006d"},
  {mods = "Super",       key = "N", chars = "\u0014\u006e"},
  {mods = "Super",       key = "O", chars = "\u0014\u006f"},
  {mods = "Super",       key = "P", chars = "\u0014\u0070"},
  {mods = "Super",       key = "Q", chars = "\u0014\u0071"},
  {mods = "Super",       key = "R", chars = "\u0014\u0072"},
  {mods = "Super",       key = "S", chars = "\u0014\u0073"},
  {mods = "Super",       key = "T", chars = "\u0014\u0074"},
  {mods = "Super",       key = "U", chars = "\u0014\u0075"},
  {mods = "Super",       key = "V", chars = "\u0014\u0076"},
  {mods = "Super",       key = "W", chars = "\u0014\u0077"},
  {mods = "Super",       key = "X", chars = "\u0014\u0078"},
  {mods = "Super",       key = "Y", chars = "\u0014\u0079"},
  {mods = "Super",       key = "Z", chars = "\u0014\u007a"},
  {mods = "Super",       key = "Z", chars = "\u0014\u007a"},

  {mods = "Control",       key = "Equals", chars = "\u0014\u003d"},
]
