[colors.primary]
background = "0x101010"
foreground = "0x909090"

[font]
size = 14.0
normal = {family = "Ricty Diminished Discord for Powerline", style = "Regular"}
bold   = {family = "Ricty Diminished Discord for Powerline", style = "Bold"}
italic = {family = "Ricty Diminished Discord for Powerline", style = "Italic"}

[keyboard]
bindings = [
  {mods = "Super",       key = "D", chars = "\u0014\u0004"},
  {mods = "Super",       key = "H", chars = "\u0014\u0008"},
  {mods = "Super",       key = "T", chars = "\u0014\u0014"},
  {mods = "Super",       key = "N", chars = "\u0014\u000E"},
  {mods = "Super|Shift", key = "D", chars = "\u0014\u0044"},
  {mods = "Super|Shift", key = "H", chars = "\u0014\u0048"},
  {mods = "Super|Shift", key = "T", chars = "\u0014\u0054"},
  {mods = "Super|Shift", key = "N", chars = "\u0014\u004e"},
]
